-- The data we are working with has an american date format.
-- This command updates our database to expect this kind of format as input
ALTER DATABASE "SQL-Challenge.db" SET datestyle = "ISO, MDY";

CREATE TABLE IF NOT EXISTS MY_SCHEMA.DEPARTMENTS (DEPT_NO VARCHAR(10) NOT NULL, DEPT_NAME VARCHAR NOT NULL, PRIMARY KEY (DEPT_NO));

CREATE TABLE IF NOT EXISTS MY_SCHEMA.TITLE (TITLE_ID VARCHAR(8) NOT NULL, TITLE VARCHAR NOT NULL, PRIMARY KEY (TITLE_ID));

CREATE TABLE IF NOT EXISTS MY_SCHEMA.EMPLOYEES (EMP_NO INT NOT NULL, EMP_TITLE_ID VARCHAR NOT NULL, BIRTH_DATE DATE NOT NULL, FIRST_NAME VARCHAR(50) NOT NULL, LAST_NAME VARCHAR(50) NOT NULL, SEX VARCHAR NOT NULL, HIRE_DATE DATE NOT NULL, PRIMARY KEY (EMP_NO), FOREIGN KEY (EMP_TITLE_ID) REFERENCES MY_SCHEMA.TITLE(TITLE_ID));

CREATE TABLE IF NOT EXISTS MY_SCHEMA.DEPT_EMP (EMP_NO INT NOT NULL, DEPT_NO VARCHAR(10) NOT NULL, PRIMARY KEY (EMP_NO, DEPT_NO), FOREIGN KEY (DEPT_NO) REFERENCES MY_SCHEMA.DEPARTMENTS(DEPT_NO), FOREIGN KEY (EMP_NO) REFERENCES MY_SCHEMA.EMPLOYEES(EMP_NO));

CREATE TABLE IF NOT EXISTS MY_SCHEMA.DEPT_MANAGER (DEPT_NO VARCHAR(10) NOT NULL, EMP_NO INT NOT NULL, PRIMARY KEY (DEPT_NO, EMP_NO), FOREIGN KEY (DEPT_NO) REFERENCES MY_SCHEMA.DEPARTMENTS(DEPT_NO), FOREIGN KEY (EMP_NO) REFERENCES MY_SCHEMA.EMPLOYEES(EMP_NO));

CREATE TABLE IF NOT EXISTS MY_SCHEMA.SALARIES (EMP_NO INT NOT NULL, SALARY INT NOT NULL, PRIMARY KEY (EMP_NO));

